src/package_json.rs
=> perf(resolver): remove extra large fields from raw package json

src/package_json.rs
This is a hash lookup, no indexing is required.
=> refactor: use FxHashMap instead of FxIndexMap for BrowserField

napi/index.d.ts, napi/package.json, napi/src/lib.rs, napi/src/options.rs, napi/tests/options.test.mjs
hi there, new to rust.
this pr is to align user options of napi bindings below with https://github.com/webpack/enhanced-resolve/blob/58464fc7cb56673c9aa849e68e6300239601e615/types.d.ts#L486-L630
- `aliasFields`
- `exportsFields`
- `mainFields`
- `modules`
=> chore(napi): align `*Fields` user options with enhanced-resolve

README.md, src/cache.rs, src/context.rs, src/lib.rs, src/tests/dependencies.rs, src/tests/extensions.rs, src/tests/incorrect_description_file.rs, src/tests/missing.rs, src/tests/mod.rs, tests/integration_test.rs
This PR adds:
* resolve_with_context API
* ResolveContext with file_dependencies and missing_dependencies
These dependencies are used for Rspack to control caching logic around module resolution.
=> feat: add file_dependencies and missing_dependencies API

src/lib.rs, src/tests/alias.rs, src/tests/missing.rs
Upstream: https://github.com/web-infra-dev/modern.js/issues/5227
Given the alias
```
'react-dom': '/node_modules/react-dom/index.js'
```
requesting `react-dom/client` would yield `/node_modules/react-dom/index.js/client.js`.
This creates a invalid missing dependency entry '/node_modules/react-dom/index.js/client.js',
for which watchpack will throw an error for `path.dirname(p)`,
```javascript
watchFile(p, startTime) {
const directory = path.dirname(p);
if (directory === p) return null;
return this.getDirectoryWatcher(directory).watch(p, startTime);
}
```
https://github.com/webpack/watchpack/blob/dc690bbaea140820f1d9c7c2ec4dff8902798ff9/lib/getWatcherManager.js#L30
=> fix: returning broken missing dependencies when alias and extensions are provided

fixtures/enhanced_resolve/test/fixtures/browser-module/package.json, fixtures/pnpm8/package.json, fixtures/pnpm8/pnpm-lock.yaml, napi/Cargo.toml, src/lib.rs, tests/resolve_test.rs
closes #58
Failed to resolve `path` in browser mode for `postcss` when
```
"exports": {
...
}
"browser": {
"./lib/terminal-highlight": false,
"source-map-js": false,
"path": false,
"url": false,
"fs": false
},
```
Are both present
There are no such test cases for this type of combination in enhanced_resolve.
=> fix: resolve "browser" field when "exports" is present

src/lib.rs, src/tsconfig.rs
=> fix: tsconfig#extends must be a string

README.md
Going over the readme, I discovered what I suspect is a simple copy-paste error.
=> Update README.md passing "require" instead of "import" to CJS resolver

fixtures/parcel/tsconfig/extends-multiple/tsconfig.json, src/lib.rs, src/tests/tsconfig_paths.rs
=> feat: support tsconfig#extends array

napi/src/lib.rs, napi/src/options.rs, src/lib.rs, src/options.rs, src/package_json.rs, tests/integration_test.rs
so we don't end up parsing unwanted fields and produce errors we don't
care about.
=> refactor: selectively parse package_json fields instead of parsing everything

src/lib.rs, src/tsconfig.rs
For performance reasons, we don't need to deserialize all the compiler options.
=> refactor: deserialize less values in tsconfig

.github/workflows/ci.yml, benches/resolver.rs, examples/resolver.rs, napi/src/lib.rs, src/options.rs, src/tests/alias.rs, src/tests/browser_field.rs, src/tests/full_specified.rs, src/tests/roots.rs
- moved `sanitize` in the first `impl` block, so we don't have two `impl` of the same struct
- we have doctects which didn't run in the CI, this PR changes the workflow to add `cargo t --doc`. By default `cargo test` doesn't run doctests
- added three new builder functions for `ResolverOptions`
- made functions of `EnforceExtension` const functions
- implemented `From` for `AliasValue` and updated its usage in the tests. Less typing :)
Added some doc tests, which pass locally. CI should pass
=> feat: add more builder functions for options

src/cache.rs, src/lib.rs
- I want hide generics of `Resolver` using `Box<dyn ...>`. And trait object require object-safey.
- `ResolverGeneric<Box<dyn FileSystem>>` is valid, but these `impl`s require `Default`. This makes `ResolverGeneric<Box<dyn FileSystem>>` totally unusable.
- `ResolverGeneric<Box<dyn FileSystem + Default>>` is not valid because `Default` trait doesn't satisfy object-safety.
---
- Changes of this PR is backforwarded.
=> feat: allow `Resolver<Box<dyn FileSystem>>` by removing unnecessary `Default` constraint

src/lib.rs
It is hard to find the matching options when there are lots of options
=> chore: print resolve options while debug tracing

src/lib.rs, src/package_json.rs, src/tests/main_field.rs
The modified test case
```rust
fn test() {
let f = super::fixture().join("restrictions");
let resolver1 = Resolver::new(ResolveOptions {
main_fields: vec!["style".into()],
..ResolveOptions::default()
});
let resolution = resolver1.resolve(&f, "pck2").map(|r| r.full_path());
assert_eq!(resolution, Ok(f.join("node_modules/pck2/index.css")));
let resolver2 = resolver1.clone_with_options(ResolveOptions {
main_fields: vec!["module".into(), "main".into()],
..ResolveOptions::default()
});
let resolution = resolver2.resolve(&f, "pck2").map(|r| r.full_path());
assert_eq!(resolution, Ok(f.join("node_modules/pck2/module.js")));
}
```
failed to revolve due to package.json caching the value of `main_fields: vec!["style".into()]`, the second resolution `main_fields: vec!["module".into(), …
=> fix: incorrect resolution when using shared resolvers with different `main_fields`

README.md, fixtures/tsconfig/cases/paths_template_variable/tsconfig1.json, fixtures/tsconfig/cases/paths_template_variable/tsconfig2.json, fixtures/tsconfig/cases/project_references/app/tsconfig.json, fixtures/tsconfig/tsconfig_template_variable.json, src/cache.rs, src/lib.rs, src/tests/tsconfig_paths.rs, src/tests/tsconfig_project_references.rs, src/tsconfig.rs
closes #129
NOTE: All tests cases are just a head replacement of `${configDir}/`, so we are constrained as such. configDir is always an absolute path, so replacing within a pass is not logical.
=> feat: substitute path that starts with `${configDir}/` in tsconfig.compilerOptions.paths

src/lib.rs, src/package_json.rs, src/tests/exports_field.rs, src/tests/imports_field.rs
relates #135
This PR removes all encapsulations around imports / exports map so we can dynamically retrieve and evaluate their values :-(
=> fix: lazily read package.json.exports for shared resolvers

napi/src/lib.rs, napi/src/options.rs, src/lib.rs, src/options.rs, src/package_json.rs, src/tests/imports_field.rs
=> feat: add `imports_fields` option

src/lib.rs, src/tests/roots.rs, tests/resolve_test.rs
Prefix for https://github.com/web-infra-dev/rspack/pull/6340
In enhanced-resolve, when resolving with `roots` failed, will continue resolve it instead of returning error
=> fix: RootsPlugin should fall through if it fails to resolve the roots

src/lib.rs, src/tests/alias.rs
Not found matched alias should return error instead of continue resolving
https://github.com/webpack/enhanced-resolve/blob/570337b969eee46120a18b62b72809a3246147da/lib/AliasPlugin.js#L134-L135
=> fix: alias not found should return error

fixtures/enhanced_resolve/test/fixtures/builtins/package.json, src/lib.rs, src/tests/builtins.rs
closes #164
According to the ESM specification https://nodejs.org/api/esm.html#resolution-and-loading-algorithm
```
// PACKAGE_RESOLVE(packageSpecifier, parentURL)
// 3. If packageSpecifier is a Node.js builtin module name, then
//   1. Return the string "node:" concatenated with packageSpecifier.
```
The returned value must be prefixed by `node:`
=> feat!: return `ResolveError:Builtin("node:{specifier}")` from package imports and exports

fixtures/enhanced_resolve/test/fixtures/browser-module/package.json, src/lib.rs, src/tests/alias.rs, src/tests/browser_field.rs
https://github.com/oxc-project/oxc-resolver/pull/170 breaks [a case in Rspack](https://github.com/web-infra-dev/rspack/actions/runs/9313088014/job/25634999631?pr=6691#step:6:988):
```js
let resolve = resolver.create({ alias: { '#': path.resolve(__dirname, '#') } });
resolve(__dirname, '#/a');
```
PR is referenced from: https://github.com/webpack/enhanced-resolve/blob/e38970852a7f89b694f1053e285195511764a900/lib/ParsePlugin.js#L33-L73
=> fix: alias value try fragment as path

src/lib.rs
I believe this comment was written incorrectly when pasted. Below is the expected one.
=> fix: comment

src/package_json.rs, tests/integration_test.rs, tests/package.json
The fields are pretty small in size, but we can try and remove the clones if necessary.
=> feat: export package.json `type` and `sideEffects` field by default for bundlers

Cargo.toml
Strips symbols from the release build and enables LTO, which results in some reduction in size of the binary.
i've not been around rust in some time so this may be absolute nonsense. if so, feel free to close
as far as i can tell, stripping symbols/debug info is a no-brainer, but LTO can reduce performance in some cases. although the benchmark seemed the same or better locally
i feel like there will be other big savings to have too (without affecting perf), but i need to read up on this stuff more.  if you have any ideas, please do let me know and im happy to try them out
=> feat: strip symbols and enable LTO

src/lib.rs
`Path::ends_with` converts the comparator to a `Path` and compares all components.
```rust
#[must_use]
pub fn ends_with<P: AsRef<Path>>(&self, child: P) -> bool {
self._ends_with(child.as_ref())
}
fn _ends_with(&self, child: &Path) -> bool {
iter_after(self.components().rev(), child.components().rev()).is_some()
}
```
`module_name` in `cached_path.path().ends_with(module_name)` is guaranteed to be a single component so this overhead can be avoided.
I also change the order of comparisons to check `node_modules` because that's the majority of the case.
=> perf: improve call to `Path::ends_with`

napi/src/lib.rs, npm/README.md, src/lib.rs
=> chore: document directory is an absolute path for `resolve(directory, specifier)`

src/error.rs, src/lib.rs, src/tests/tsconfig_project_references.rs, src/tsconfig.rs
Self-reference in tsconfig will cause short-lived invaild cache, more info see https://github.com/oxc-project/oxc-resolver/pull/210.
This PR will throw a TsconfigSelfReference error.
=> fix: tsconfig self-reference throw error

src/cache.rs, src/file_system.rs
Reduce one redundant fs::symlink_metadata system call.
=> perf: use custom canonicalize impl to avoid usless syscall

src/file_system.rs
I should have checked the file changes before click the **resolve conversation** button :(
=> fix: remove `#[cfg(target_os = "windows")]` logic in `canonicalize`

napi/index.d.ts, napi/src/lib.rs
See https://github.com/oxc-project/oxc-node/blob/main/src/lib.rs#L345-L358 for the context:
We need to know the module type for resolved paths, so we can pass it to the Node.js import loader hook.
This can also fix https://github.com/swc-project/swc-node/issues/788
=> feat(napi): expose module type info in ResolveResult

examples/resolver.rs, fixtures/pnpm/package.json, pnpm-lock.yaml, src/error.rs, src/lib.rs, src/tests/exports_field.rs, src/tests/extension_alias.rs, tests/resolve_test.rs
closes #227
Managed to figure this out after stepping through https://github.com/webpack/enhanced-resolve/blob/main/lib/ExtensionAliasPlugin.js
=> fix: resolve module `ipaddr.js` correctly when `extensionAlias` is provided

src/error.rs, src/lib.rs, src/tests/exports_field.rs, src/tests/extension_alias.rs
It is now displayed as `Cannot resolve 'index.mjs' with extension aliases 'index.mts' in ...`
=> feat: show tried extension aliases in `ResolveError::ExtensionAlias`

src/error.rs, src/lib.rs, src/tests/builtins.rs
`ResolveError::Builtin::is_runtime_module` can be used to determine whether the original specifier was prefixed with `node:` or not.
=> feat!: add `ResolveError::Builtin::is_runtime_module`

src/cache.rs, src/package_json.rs, src/specifier.rs
=> refactor: clean up elided lifetimes

src/file_system.rs
=> fix: use `fs::canonicalize` to cover symlink edge cases

CHANGELOG.md, Cargo.lock, Cargo.toml, npm/package.json
* `oxc_resolver`: 1.12.0 -> 2.0.0
<blockquote>
- [**breaking**] add `ResolveError::Builtin::prefixed_with_node_colon` ([#272](https://github.com/oxc-project/oxc-resolver/pull/272))
- use `fs::canonicalize` to cover symlink edge cases ([#284](https://github.com/oxc-project/oxc-resolver/pull/284))
- extensionAlias cannot resolve mathjs ([#273](https://github.com/oxc-project/oxc-resolver/pull/273))
- fix test warning
- relax versions for downstream use
- use default features for `rustc-hash`
- apply latest `cargo +nightly fmt` ([#281](https://github.com/oxc-project/oxc-resolver/pull/281))
- add more clippy fixes ([#279](https://github.com/oxc-project/oxc-resolver/pull/279))
- clean up elided lifetimes …
=> chore: release v2.0.0

CHANGELOG.md, Cargo.lock, Cargo.toml, npm/package.json
* `oxc_resolver`: 2.0.0 -> 2.0.1 (✓ API compatible changes)
<blockquote>
- `cargo upgrade` && `pnpm upgrade`
- bring back the symlink optimization ([#298](https://github.com/oxc-project/oxc-resolver/pull/298))
- *(deps)* update rust crate criterion2 to v2
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v2.0.1

fixtures/pnp/.gitignore
Since `.yarn/cache` files are not committed in the repo, I guess this repo does not use the Zero-Installs feature. In that case, `.yarn/cache` should be gitignored.
https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored
=> chore: add .yarn to gitignore

src/tests/symlink.rs
When calling `fs::remove_file` against a symlink pointing a directory on Windows, `PermissionDenied` error was happening. This was causing the symlink tests to pass only for the first time.
~~But this makes the symlink tests to fail on Windows (https://github.com/oxc-project/oxc-resolver/issues/308). 🫠~~ I was able to fix them.
fixes #308
=> test: fix symlink test init on windows

justfile
`cargo benchmark` throws "no such command" on my machine. Probably this should be `cargo bench`?
=> chore: fix just benchmark

Cargo.lock, Cargo.toml, fixtures/pnpm/longfilename/index.js, fixtures/pnpm/longfilename/package.json, fixtures/pnpm/package.json, pnpm-lock.yaml, src/file_system.rs, tests/resolve_test.rs
=> fix: use same UNC path normalization logic with libuv

src/lib.rs, src/tests/resolve.rs, src/tests/roots.rs
When calling `resolve(base_dir, "/?test.css")`, a panic happened.
=> fix: don't panic when resolving `/` with `roots`

CHANGELOG.md, Cargo.lock, Cargo.toml, npm/package.json
* `oxc_resolver`: 2.0.1 -> 2.1.0 (✓ API compatible changes)
<blockquote>
- add `Resolver::resolve_tsconfig` API ([#312](https://github.com/oxc-project/oxc-resolver/pull/312))
- don't panic when resolving `/` with `roots` ([#310](https://github.com/oxc-project/oxc-resolver/pull/310))
- use same UNC path normalization logic with libuv ([#306](https://github.com/oxc-project/oxc-resolver/pull/306))
- *(deps)* update rust crates to v1.0.215
- fix symlink test init on windows ([#307](https://github.com/oxc-project/oxc-resolver/pull/307))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release v2.1.0

src/options.rs
Noticed that this comment is incorrect. Extensions are required to be prefixed with a `.`
=> docs: mention extension must start with a `.` in `with_extension`

src/cache.rs, src/lib.rs
=> perf: reduce memory allocation by using a thread_local path for path methods

CHANGELOG.md, Cargo.lock, Cargo.toml, npm/package.json
* `oxc_resolver`: 2.1.0 -> 2.1.1 (✓ API compatible changes)
<blockquote>
- reduce hash while resolving package.json ([#319](https://github.com/oxc-project/oxc-resolver/pull/319))
- reduce memory allocation while normalizing package path ([#318](https://github.com/oxc-project/oxc-resolver/pull/318))
- reduce memory allocation while resolving package.json ([#317](https://github.com/oxc-project/oxc-resolver/pull/317))
- use `path.as_os_str().hash()` instead of `path.hash()` ([#316](https://github.com/oxc-project/oxc-resolver/pull/316))
- remove the deprecated simdutf8 aarch64_neon feature
- reduce memory allocation by using a thread_local path for path methods ([#315](https://github.com/oxc-project/oxc-resolver/pull/315))
- add more data …
=> chore: release v2.1.1

src/cache.rs, src/tests/resolve.rs
=> feat: faster and stable path hash for the cache

CHANGELOG.md, Cargo.lock, Cargo.toml, npm/package.json
* `oxc_resolver`: 2.1.1 -> 3.0.0 (⚠️ API breaking changes)
```
--- failure trait_method_added: pub trait method added ---
Description:
A non-sealed public trait added a new method without a default implementation, which breaks downstream implementations of the trait
ref: https://doc.rust-lang.org/cargo/reference/semver.html#trait-new-item-no-default
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.37.0/src/lints/trait_method_added.ron
Failed in:
trait method oxc_resolver::FileSystem::read_link in file /tmp/.tmptmsXac/oxc-resolver/src/file_system.rs:52
--- failure trait_method_missing: pub trait method removed or renamed ---
Description:
A trait method is no longer callable, and may have been renamed or removed entirely.
ref: …
```
=> chore: release v3.0.0

src/cache.rs
There's a slight cost of the runtime borrow check but I guess it's negligible.
=> refactor: replace UnsafeCell with RefCell

src/cache.rs, src/tests/resolve.rs
=> fix: normalize resolved result on Windows for root

Cargo.toml, src/cache.rs, src/context.rs, src/error.rs, src/file_system.rs, src/fs_cache.rs, src/lib.rs, src/tests/alias.rs, src/tests/dependencies.rs, src/tests/exports_field.rs, src/tests/fallback.rs, src/tests/full_specified.rs, src/tests/imports_field.rs, src/tests/simple.rs, src/tests/tsconfig_paths.rs, src/tsconfig.rs
This PR makes the cache fully generic by introducing a `Cache` trait, and renaming the existing `Cache` to `FsCache`.
The `FileSystem` trait still exists, but is only relevant still for users of `FsCache`. By keeping the trait, I hope to minimize the amount of breaking changes, even though some still remain.
The most notable breaking change is that `ResolverGeneric::new_with_file_system(fs, ...)` has become `ResolverGeneric::new_with_cache(Arc::new(FsCache::new(fs)), ...)`.
Both `FsCache` and `FileSystem` are now behind a `fs_cache` feature flag, which is enabled by default.
I am actually considering to make both the `PackageJson` and `TsConfig` types generic as well (Biome already has its own, which ideally we would use directly for our custom `Cache` implementation). This should be …
=> feat!: generic fs cache `type Resolver = ResolverGeneric<FsCache<FileSystemOs>>`

Cargo.lock, Cargo.toml, src/fs_cache.rs
This PR replaces uses of `dashmap` in the `Cache` with `papaya`: https://github.com/ibraheemdev/papaya/
`papaya` is designed for read-heavy workloads, which seems quite fitting for your caching use case. We've also switched to it in Biome and are getting good results.
Note this PR currently depends on an unmerged feature I proposed, so I'm leaving it in Draft until this is merged: https://github.com/ibraheemdev/papaya/pull/45
Performance results on my machine:
```
Benchmarking resolver/single-thread: Collecting 100 samples in estimated 5.0029 s (91k iteresolver/single-thread  time:   [53.564 µs 53.785 µs 54.015 µs]
change: [−13.249% −11.794% −10.385%] (p = 0.00 < 0.05)
Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
2 (2.00%) high mild
6 (6.00%) high severe …
```
=> Use papaya instead of dashmap

Cargo.toml, napi/src/lib.rs, src/cache.rs, src/error.rs, src/fs_cache.rs, src/lib.rs, src/package_json.rs, src/package_json_serde.rs, src/resolution.rs, src/tests/exports_field.rs, src/tests/imports_field.rs, src/tests/mod.rs, src/tests/resolution.rs, src/tests/tsconfig_paths.rs, src/tsconfig.rs, src/tsconfig_serde.rs, tests/integration_test.rs
This introduces `PackageJson` and `TsConfig` traits. The old structs have been renamed to `PackageJsonSerde` and TsConfigSerde` respectively. Both are behind the `fs_cache` feature flag now. `serde` as a dependency has become optional and is only needed for the `fs_cache` feature too.
For now, I have opted not to replace the `FileSystem::read_to_string()` method with trait-specific versions yet, since this functionality is now all encapsulated within the `FsCache`. Consumers that wish to use custom implementation of the manifest traits most likely want to use a custom cache altogether (I know this will be true for Biome at least), so I didn't see much reason for additional complexity and breaking changes there now.
~~I'm still working on a Biome PoC based on this, so I'll keep the PR on …
=> Manifest traits

src/tsconfig_serde.rs
related issues: 
1. https://github.com/rolldown/rolldown/issues/2296
2. https://github.com/rolldown/rolldown/issues/3473
These issues require rolldown read the `tsconfig.json` and merge related options to `oxc-transform`
=> feat: add more fields in tsconfig#CompilerOptionsSerde

src/lib.rs, src/tests/alias.rs
```
alias: {
'@*': path.resolve(__dirname, 'src/*'), // maps `@something` to `path/to/something`
}
```
Ported from https://github.com/webpack/enhanced-resolve/pull/439
Please note there is a small behaviour difference when compared to TypeScript's path alias resolve:
In TypeScript, when multiple patterns match a module specifier, the pattern with the longest matching prefix before any * token is used:
https://www.typescriptlang.org/docs/handbook/modules/reference.html#wildcard-substitutions
In enhanced-resolved's alias plugin, first matched alias key (in declaration order) wins.
closes #385
closes #386
=> feat: support wildcard `*` in alias plugin

src/tsconfig_serde.rs
1. related to https://github.com/rolldown/rolldown/issues/3777, rolldown needs this field to merge tsc options.
=> feat: deserialize `verbatim_module_syntax` from compilerOptions

fixtures/enhanced_resolve/test/fixtures/exports-field/node_modules/exports-field/package.json, fixtures/enhanced_resolve/test/fixtures/imports-field/package.json, src/lib.rs, src/tests/exports_field.rs, src/tests/imports_field.rs
package.json `exports` and `imports` field con contain queries or fragments:
`"exports": { ".": { "default": "./foo.js?query#fragment" }`
closes #417
=> fix: handle query and fragment in pacakge.json `exports` and `imports` field

.github/workflows/release-napi.yml, napi/Cargo.toml, napi/src/lib.rs, npm/package.json
=> ci(release-napi): support `riscv64gc-unknown-linux-gnu` and `s390x-unknown-linux-gnu`

src/tsconfig_serde.rs
Related to https://github.com/rolldown/rolldown/pull/4174
Align with [rolldown-vite](https://github.com/vitejs/rolldown-vite/blob/da2cc9626520e2556c0dd0b5273dbd1aa4a5a7c8/packages/vite/src/node/plugins/oxc.ts#L146-L190)
In fact, `preserveValueImports` and `importsNotUsedAsValues` have been deprecated and replaced by `verbatimModuleSyntax`. However, for compatibility and alignment with `rolldown-vite`, I had to suggest adding them.
=> feat: deserialize `preserve_value_imports` and `imports_not_used_as_values` from `compilerOptions`

src/error.rs, src/file_system.rs, src/fs_cache.rs, src/lib.rs, src/windows.rs
Fixes #454 
This PR changed the name and return type of `strip_windows_prefix` to `try_strip_windows_prefix`, allowing it to return `None` to indicate unsupported [DOS device paths](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths).
Most significantly, symlinks referring to a drive without drive letter, usually accessed via a mount point (Mounted Volume), should not be resolved at all, as nodejs `import`/`require` does not support such properly, as of Node 22.
This PR also rectified the [UNC path](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths) resolution to prepend the `"\\"` portion to the path.
=> fix: properly handle DOS device paths in strip_windows_prefix

fixtures/misc/package-json-with-bom/package.json, fixtures/tsconfig/cases/with-bom/tsconfig.json, src/package_json_serde.rs, src/tests/tsconfig_paths.rs, src/tsconfig_serde.rs, tests/resolve_test.rs
Node supports `package.json` with UTF-8 BOM and TypeScript supports `tsconfig.json` with UTF-8 BOM.
An error was happening for these cases.
=> fix: handle package.json and tsconfig.json with BOM

justfile
I sorted the list as alphabetize
=> chore: `cargo-shear` is required for `fmt`

README.md, napi/index.d.ts, napi/src/lib.rs, napi/src/options.rs, src/cache.rs, src/fs_cache.rs, src/lib.rs, src/options.rs, src/tests/alias.rs, src/tests/dependencies.rs, src/tests/fallback.rs, src/tests/resolve.rs, tests/integration_test.rs
This reverts commit f64911c71096199ce32ee8282e9e6f7d9fd25c9b.
closes #502
closes #493
I don't have have a clear understanding of how .d.ts resolution works so reverting the previous commit.
=> Revert "refactor!: remove `modules` options (#484)"

README.md, napi/Cargo.toml, napi/src/lib.rs
=> feat(napi): add `tracing-subscriber` feature; turned on by default

src/error.rs, src/lib.rs, src/tsconfig_context.rs, tests/integration_test.rs, tests/tsconfig_circular_reference_a.json, tests/tsconfig_circular_reference_b.json, tests/tsconfig_self_reference.json
When there's a circular `tsconfig` extends, oxc-resolver crashed with `Segmentation fault (core dumped)`.
This PR fixes that.
In this case, TypeScript outputs errors like:
```
$ pnpm tsc --noEmit -p tsconfig_self_reference.json
error TS18000: Circularity detected while resolving configuration: /home/green/workspace/oxc-resolver/tests/tsconfig_self_reference.json -> /home/green/workspace/oxc-resolver/tests/tsconfig_self_reference.json
$ pnpm tsc --noEmit -p tsconfig_circular_reference_a.json 
error TS18000: Circularity detected while resolving configuration: /home/green/workspace/oxc-resolver/tests/tsconfig_circular_reference_a.json -> /home/green/workspace/oxc-resolver/tests/tsconfig_circular_reference_b.json -> /home/green/workspace/oxc-resolver/tests/tsconfig_circular_reference_a.json …
```
=> fix: avoid crash when encountering tsconfig circular extends

napi/index.d.ts, napi/src/lib.rs, napi/src/options.rs, src/lib.rs, src/options.rs, src/tests/exports_field.rs
closes #571
This is not part of the spec but some vite projects rely on this behavior.
Opt-in by `allowPackageExportsInDirectoryResolve: true`.
See
* https://github.com/vitejs/vite/pull/20252
* https://github.com/nodejs/node/issues/58827
=> feat(resolver): allow `exports` field in `require('../directory')`

README.md, napi/Cargo.toml, napi/index.d.ts, napi/index.js, napi/patch.mjs, napi/src/lib.rs, napi/src/options.rs, src/cache.rs, src/fs_cache.rs, src/lib.rs, src/options.rs, src/tests/pnp.rs
The current manifest file (`.pnp.cjs`) lookup technique does not work when `enableGlobalCache` is set to `true`, which is the default behavior for yarn.
Instead, we try and find the closest pnp maniest from cwd.
This will break the multi-project case mentioned in https://yarnpkg.com/advanced/pnp-spec#find_pnp_manifest, but I think this is an acceptable trade off.
For napi, I set `process.env.OXC_RESOLVER_YARN_PNP` in `napi/index.js` so the Rust side can enable yarn pnp accordingly.
=> feat(resolver): rework yarn manifest file look up

.github/workflows/ci.yml, justfile, src/file_system.rs, src/lib.rs, src/tests/memory_fs.rs
Running fs operations through yarn pnp incurs significant performance cost, caused by running `VPath::from(path)` on every path.
Feature gate this through a runtime flag,
because a bundler can enable `yarn_pnp` feature but run the resolver without presence of `yarn`.
=> feat: add `yarn_pnp` logic to `FileSystem`

src/lib.rs
Enables matching on the extends field of the tsconfig struct.
See https://github.com/oxc-project/oxc-resolver/issues/606
=> Expose the `ExtendsField` enum of TsConfig

src/lib.rs, src/tests/exports_field.rs
Resolving `package?query#fragment` to packages with exports field is allowed in Vite to allow things like `css-package?url`, `wasm-package?init`. This was not allowed by oxc-resolver and this PR allows that.
The current behavior of oxc-resolver comes from this change in enhanced-resolve (https://github.com/webpack/enhanced-resolve/pull/225). This PR adds tests that disallows `pkg?foo` but allows `pkg/nested?foo`.
This current behavior doesn't make sense to me. Both `pkg?foo` and `pkg/nested?foo` are not allowed by Node and I don't find a reason to treat them differently.
fixes https://github.com/vitejs/rolldown-vite/issues/382
refs https://github.com/oxc-project/oxc-resolver/commit/97dfb1a3f81569b32c2477470ff6cc685ebb2a9d
=> fix: allow resolving `package?query#fragment` for packages with exports field

fixtures/tsconfig/cases/extends-compiler-options/base-tsconfig.json, src/tests/tsconfig_extends.rs, src/tsconfig.rs
Related to https://github.com/rolldown/rolldown/issues/5867
The extension checks for `include` and `exclude` paths need to take `allowJs` into account.
=> feat(tsconfig) support `allowJs` in `compilerOptions`

CHANGELOG.md, Cargo.lock, Cargo.toml, napi/Cargo.toml, napi/index.js, package.json
* `oxc_resolver`: 11.7.2 -> 11.8.0
* `oxc_resolver_napi`: 11.7.2 -> 11.8.0
<blockquote>
- add benchmark for package.json deserialization ([#698](https://github.com/oxc-project/oxc-resolver/pull/698)) (by @Boshen) - #698
- use `memmap` to speed up file reading ([#696](https://github.com/oxc-project/oxc-resolver/pull/696)) (by @Boshen) - #696
* @Boshen
* @renovate[bot]
</blockquote>
</p></details>
---
=> chore: release v11.8.0

Cargo.lock, Cargo.toml, src/file_system.rs
Reverts oxc-project/oxc-resolver#696
Performance regression shown in 
* https://github.com/rolldown/rolldown/pull/6224
=> Revert "perf: use `memmap` to speed up file reading"

CHANGELOG.md, Cargo.lock, Cargo.toml, napi/Cargo.toml
* `oxc_resolver`: 11.8.0 -> 11.8.1
* `oxc_resolver_napi`: 11.8.0 -> 11.8.1
<blockquote>
- Revert "perf: use `memmap` to speed up file reading" ([#701](https://github.com/oxc-project/oxc-resolver/pull/701)) (by @Boshen) - #701
* @Boshen
</blockquote>
</p></details>
---
=> chore: release v11.8.1

CHANGELOG.md, Cargo.lock, Cargo.toml, napi/Cargo.toml, napi/index.js, package.json
* `oxc_resolver`: 11.8.1 -> 11.8.2
* `oxc_resolver_napi`: 11.8.1 -> 11.8.2
<blockquote>
- bypass file system read cache if memory cache is available ([#707](https://github.com/oxc-project/oxc-resolver/pull/707)) (by @Brooooooklyn) - #707
- enable Windows global pnp case ([#703](https://github.com/oxc-project/oxc-resolver/pull/703)) (by @JounQin) - #703
* @Brooooooklyn
* @JounQin
</blockquote>
</p></details>
---
=> chore: release v11.8.2

CHANGELOG.md, Cargo.lock, Cargo.toml, napi/Cargo.toml, napi/index.js, package.json
* `oxc_resolver`: 11.8.3 -> 11.8.4
* `oxc_resolver_napi`: 11.8.3 -> 11.8.4
<blockquote>
- ensure canonicalized paths remain accessible via strong references ([#733](https://github.com/oxc-project/oxc-resolver/pull/733)) (by @Boshen) - #733
- mark error path functions as #[cold] for better optimization ([#729](https://github.com/oxc-project/oxc-resolver/pull/729)) (by @Boshen) - #729
* @Boshen
</blockquote>
</p></details>
---
=> chore: release v11.8.4

.github/workflows/ci.yml, Cargo.toml, src/lib.rs, src/tests/resolve.rs
fixes #716
In https://github.com/unrs/unrs-resolver/issues/127, the original issue statement was "file: protocol is required to be used on Windows for import statement."
There are no integrations for such cases and only 1 unit test, so limit it to windows.
=> feat: only resolve file:// protocol on windows

CHANGELOG.md, Cargo.lock, Cargo.toml, napi/Cargo.toml
* `oxc_resolver`: 11.8.4 -> 11.9.0
* `oxc_resolver_napi`: 11.8.4 -> 11.9.0
<blockquote>
- only resolve file:// protocol on windows ([#737](https://github.com/oxc-project/oxc-resolver/pull/737)) (by @Boshen) - #737
- improve test coverage for edge cases ([#740](https://github.com/oxc-project/oxc-resolver/pull/740)) (by @Boshen) - #740
- improve coverage for check_restrictions ([#739](https://github.com/oxc-project/oxc-resolver/pull/739)) (by @Boshen) - #739
* @Boshen
</blockquote>
</p></details>
---
=> chore: release v11.9.0
